<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>
  <form id="myForm" method="POST" action="{{ route('api.webhook') }}">
    @csrf
    <label for="event">Event</label>
    <select id="event" name="event">
      <option value="push">push</option>
      <option value="issues" >issues</option>
      <option value="issue_comment" selected>issue_comment</option>
      <option value="pull_request">pull_request</option>
      <option value="pull_request_review">pull_request_review</option>
      <option value="pull_request_review_comment">pull_request_review_comment</option>
    </select>
    <input type="text" name="payload" id='payload' value='

{
    "action": "created",
    "comment": {
        "url": "https://api.github.com/repos/lucasvanbriemen/github/pulls/comments/2380015313",
        "pull_request_review_id": 3269029492,
        "id": 2380015313,
        "node_id": "PRRC_kwDOPrFya86N3CbR",
        "diff_hunk": "",
        "path": "app/Services/ComponentService.php",
        "commit_id": "51fac72ac70bd2dd25e6ad1005c996598179ca05",
        "original_commit_id": "51fac72ac70bd2dd25e6ad1005c996598179ca05",
        "user": {
            "login": "lukaas-007",
            "id": 117530797,
            "node_id": "U_kgDOBwFgrQ",
            "avatar_url": "https://avatars.githubusercontent.com/u/117530797?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/lukaas-007",
            "html_url": "https://github.com/lukaas-007",
            "followers_url": "https://api.github.com/users/lukaas-007/followers",
            "following_url": "https://api.github.com/users/lukaas-007/following{/other_user}",
            "gists_url": "https://api.github.com/users/lukaas-007/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/lukaas-007/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/lukaas-007/subscriptions",
            "organizations_url": "https://api.github.com/users/lukaas-007/orgs",
            "repos_url": "https://api.github.com/users/lukaas-007/repos",
            "events_url": "https://api.github.com/users/lukaas-007/events{/privacy}",
            "received_events_url": "https://api.github.com/users/lukaas-007/received_events",
            "type": "User",
            "user_view_type": "public",
            "site_admin": false
        },
        "body": "i dont really like this code, wdyt?",
        "created_at": "2025-09-25T18:39:26Z",
        "updated_at": "2025-09-25T18:39:26Z",
        "html_url": "https://github.com/lucasvanbriemen/github/pull/6#discussion_r2380015313",
        "pull_request_url": "https://api.github.com/repos/lucasvanbriemen/github/pulls/6",
        "author_association": "CONTRIBUTOR",
        "_links": {
            "self": {
                "href": "https://api.github.com/repos/lucasvanbriemen/github/pulls/comments/2380015313"
            },
            "html": {
                "href": "https://github.com/lucasvanbriemen/github/pull/6#discussion_r2380015313"
            },
            "pull_request": {
                "href": "https://api.github.com/repos/lucasvanbriemen/github/pulls/6"
            }
        },
        "reactions": {
            "url": "https://api.github.com/repos/lucasvanbriemen/github/pulls/comments/2380015313/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "start_line": 203,
        "original_start_line": 203,
        "start_side": "LEFT",
        "line": 222,
        "original_line": 222,
        "side": "LEFT",
        "original_position": 222,
        "position": 222,
        "subject_type": "line"
    },
    "pull_request": {
        "url": "https://api.github.com/repos/lucasvanbriemen/github/pulls/6",
        "id": 2861535323,
        "node_id": "PR_kwDOPrFya86qj5Bb",
        "html_url": "https://github.com/lucasvanbriemen/github/pull/6",
        "diff_url": "https://github.com/lucasvanbriemen/github/pull/6.diff",
        "patch_url": "https://github.com/lucasvanbriemen/github/pull/6.patch",
        "issue_url": "https://api.github.com/repos/lucasvanbriemen/github/issues/6",
        "number": 6,
        "state": "open",
        "locked": false,
        "title": "Merge develop to master",
        "user": {
            "login": "lukaas-007",
            "id": 117530797,
            "node_id": "U_kgDOBwFgrQ",
            "avatar_url": "https://avatars.githubusercontent.com/u/117530797?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/lukaas-007",
            "html_url": "https://github.com/lukaas-007",
            "followers_url": "https://api.github.com/users/lukaas-007/followers",
            "following_url": "https://api.github.com/users/lukaas-007/following{/other_user}",
            "gists_url": "https://api.github.com/users/lukaas-007/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/lukaas-007/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/lukaas-007/subscriptions",
            "organizations_url": "https://api.github.com/users/lukaas-007/orgs",
            "repos_url": "https://api.github.com/users/lukaas-007/repos",
            "events_url": "https://api.github.com/users/lukaas-007/events{/privacy}",
            "received_events_url": "https://api.github.com/users/lukaas-007/received_events",
            "type": "User",
            "user_view_type": "public",
            "site_admin": false
        },
        "body": "PR desc",
        "created_at": "2025-09-25T18:04:32Z",
        "updated_at": "2025-09-25T18:39:26Z",
        "closed_at": null,
        "merged_at": null,
        "merge_commit_sha": null,
        "assignee": {
            "login": "lukaas-007",
            "id": 117530797,
            "node_id": "U_kgDOBwFgrQ",
            "avatar_url": "https://avatars.githubusercontent.com/u/117530797?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/lukaas-007",
            "html_url": "https://github.com/lukaas-007",
            "followers_url": "https://api.github.com/users/lukaas-007/followers",
            "following_url": "https://api.github.com/users/lukaas-007/following{/other_user}",
            "gists_url": "https://api.github.com/users/lukaas-007/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/lukaas-007/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/lukaas-007/subscriptions",
            "organizations_url": "https://api.github.com/users/lukaas-007/orgs",
            "repos_url": "https://api.github.com/users/lukaas-007/repos",
            "events_url": "https://api.github.com/users/lukaas-007/events{/privacy}",
            "received_events_url": "https://api.github.com/users/lukaas-007/received_events",
            "type": "User",
            "user_view_type": "public",
            "site_admin": false
        },
        "assignees": [
            {
                "login": "lukaas-007",
                "id": 117530797,
                "node_id": "U_kgDOBwFgrQ",
                "avatar_url": "https://avatars.githubusercontent.com/u/117530797?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/lukaas-007",
                "html_url": "https://github.com/lukaas-007",
                "followers_url": "https://api.github.com/users/lukaas-007/followers",
                "following_url": "https://api.github.com/users/lukaas-007/following{/other_user}",
                "gists_url": "https://api.github.com/users/lukaas-007/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/lukaas-007/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/lukaas-007/subscriptions",
                "organizations_url": "https://api.github.com/users/lukaas-007/orgs",
                "repos_url": "https://api.github.com/users/lukaas-007/repos",
                "events_url": "https://api.github.com/users/lukaas-007/events{/privacy}",
                "received_events_url": "https://api.github.com/users/lukaas-007/received_events",
                "type": "User",
                "user_view_type": "public",
                "site_admin": false
            }
        ],
        "requested_reviewers": [],
        "requested_teams": [],
        "labels": [
            {
                "id": 9237371869,
                "node_id": "LA_kwDOPrFya88AAAACJpcb3Q",
                "url": "https://api.github.com/repos/lucasvanbriemen/github/labels/wontfix",
                "name": "wontfix",
                "color": "ffffff",
                "default": true,
                "description": "This will not be worked on"
            }
        ],
        "milestone": null,
        "draft": false,
        "commits_url": "https://api.github.com/repos/lucasvanbriemen/github/pulls/6/commits",
        "review_comments_url": "https://api.github.com/repos/lucasvanbriemen/github/pulls/6/comments",
        "review_comment_url": "https://api.github.com/repos/lucasvanbriemen/github/pulls/comments{/number}",
        "comments_url": "https://api.github.com/repos/lucasvanbriemen/github/issues/6/comments",
        "statuses_url": "https://api.github.com/repos/lucasvanbriemen/github/statuses/51fac72ac70bd2dd25e6ad1005c996598179ca05",
        "head": {
            "label": "lucasvanbriemen:develop",
            "ref": "develop",
            "sha": "51fac72ac70bd2dd25e6ad1005c996598179ca05",
            "user": {
                "login": "lucasvanbriemen",
                "id": 222973435,
                "node_id": "O_kgDODUpN-w",
                "avatar_url": "https://avatars.githubusercontent.com/u/222973435?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/lucasvanbriemen",
                "html_url": "https://github.com/lucasvanbriemen",
                "followers_url": "https://api.github.com/users/lucasvanbriemen/followers",
                "following_url": "https://api.github.com/users/lucasvanbriemen/following{/other_user}",
                "gists_url": "https://api.github.com/users/lucasvanbriemen/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/lucasvanbriemen/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/lucasvanbriemen/subscriptions",
                "organizations_url": "https://api.github.com/users/lucasvanbriemen/orgs",
                "repos_url": "https://api.github.com/users/lucasvanbriemen/repos",
                "events_url": "https://api.github.com/users/lucasvanbriemen/events{/privacy}",
                "received_events_url": "https://api.github.com/users/lucasvanbriemen/received_events",
                "type": "Organization",
                "user_view_type": "public",
                "site_admin": false
            },
            "repo": {
                "id": 1051816555,
                "node_id": "R_kgDOPrFyaw",
                "name": "github",
                "full_name": "lucasvanbriemen/github",
                "private": false,
                "owner": {
                    "login": "lucasvanbriemen",
                    "id": 222973435,
                    "node_id": "O_kgDODUpN-w",
                    "avatar_url": "https://avatars.githubusercontent.com/u/222973435?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/lucasvanbriemen",
                    "html_url": "https://github.com/lucasvanbriemen",
                    "followers_url": "https://api.github.com/users/lucasvanbriemen/followers",
                    "following_url": "https://api.github.com/users/lucasvanbriemen/following{/other_user}",
                    "gists_url": "https://api.github.com/users/lucasvanbriemen/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/lucasvanbriemen/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/lucasvanbriemen/subscriptions",
                    "organizations_url": "https://api.github.com/users/lucasvanbriemen/orgs",
                    "repos_url": "https://api.github.com/users/lucasvanbriemen/repos",
                    "events_url": "https://api.github.com/users/lucasvanbriemen/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/lucasvanbriemen/received_events",
                    "type": "Organization",
                    "user_view_type": "public",
                    "site_admin": false
                },
                "html_url": "https://github.com/lucasvanbriemen/github",
                "description": null,
                "fork": false,
                "url": "https://api.github.com/repos/lucasvanbriemen/github",
                "forks_url": "https://api.github.com/repos/lucasvanbriemen/github/forks",
                "keys_url": "https://api.github.com/repos/lucasvanbriemen/github/keys{/key_id}",
                "collaborators_url": "https://api.github.com/repos/lucasvanbriemen/github/collaborators{/collaborator}",
                "teams_url": "https://api.github.com/repos/lucasvanbriemen/github/teams",
                "hooks_url": "https://api.github.com/repos/lucasvanbriemen/github/hooks",
                "issue_events_url": "https://api.github.com/repos/lucasvanbriemen/github/issues/events{/number}",
                "events_url": "https://api.github.com/repos/lucasvanbriemen/github/events",
                "assignees_url": "https://api.github.com/repos/lucasvanbriemen/github/assignees{/user}",
                "branches_url": "https://api.github.com/repos/lucasvanbriemen/github/branches{/branch}",
                "tags_url": "https://api.github.com/repos/lucasvanbriemen/github/tags",
                "blobs_url": "https://api.github.com/repos/lucasvanbriemen/github/git/blobs{/sha}",
                "git_tags_url": "https://api.github.com/repos/lucasvanbriemen/github/git/tags{/sha}",
                "git_refs_url": "https://api.github.com/repos/lucasvanbriemen/github/git/refs{/sha}",
                "trees_url": "https://api.github.com/repos/lucasvanbriemen/github/git/trees{/sha}",
                "statuses_url": "https://api.github.com/repos/lucasvanbriemen/github/statuses/{sha}",
                "languages_url": "https://api.github.com/repos/lucasvanbriemen/github/languages",
                "stargazers_url": "https://api.github.com/repos/lucasvanbriemen/github/stargazers",
                "contributors_url": "https://api.github.com/repos/lucasvanbriemen/github/contributors",
                "subscribers_url": "https://api.github.com/repos/lucasvanbriemen/github/subscribers",
                "subscription_url": "https://api.github.com/repos/lucasvanbriemen/github/subscription",
                "commits_url": "https://api.github.com/repos/lucasvanbriemen/github/commits{/sha}",
                "git_commits_url": "https://api.github.com/repos/lucasvanbriemen/github/git/commits{/sha}",
                "comments_url": "https://api.github.com/repos/lucasvanbriemen/github/comments{/number}",
                "issue_comment_url": "https://api.github.com/repos/lucasvanbriemen/github/issues/comments{/number}",
                "contents_url": "https://api.github.com/repos/lucasvanbriemen/github/contents/{+path}",
                "compare_url": "https://api.github.com/repos/lucasvanbriemen/github/compare/{base}...{head}",
                "merges_url": "https://api.github.com/repos/lucasvanbriemen/github/merges",
                "archive_url": "https://api.github.com/repos/lucasvanbriemen/github/{archive_format}{/ref}",
                "downloads_url": "https://api.github.com/repos/lucasvanbriemen/github/downloads",
                "issues_url": "https://api.github.com/repos/lucasvanbriemen/github/issues{/number}",
                "pulls_url": "https://api.github.com/repos/lucasvanbriemen/github/pulls{/number}",
                "milestones_url": "https://api.github.com/repos/lucasvanbriemen/github/milestones{/number}",
                "notifications_url": "https://api.github.com/repos/lucasvanbriemen/github/notifications{?since,all,participating}",
                "labels_url": "https://api.github.com/repos/lucasvanbriemen/github/labels{/name}",
                "releases_url": "https://api.github.com/repos/lucasvanbriemen/github/releases{/id}",
                "deployments_url": "https://api.github.com/repos/lucasvanbriemen/github/deployments",
                "created_at": "2025-09-06T19:24:58Z",
                "updated_at": "2025-09-25T18:33:21Z",
                "pushed_at": "2025-09-25T18:33:18Z",
                "git_url": "git://github.com/lucasvanbriemen/github.git",
                "ssh_url": "git@github.com:lucasvanbriemen/github.git",
                "clone_url": "https://github.com/lucasvanbriemen/github.git",
                "svn_url": "https://github.com/lucasvanbriemen/github",
                "homepage": null,
                "size": 526,
                "stargazers_count": 0,
                "watchers_count": 0,
                "language": "PHP",
                "has_issues": true,
                "has_projects": true,
                "has_downloads": true,
                "has_wiki": false,
                "has_pages": false,
                "has_discussions": false,
                "forks_count": 0,
                "mirror_url": null,
                "archived": false,
                "disabled": false,
                "open_issues_count": 4,
                "license": null,
                "allow_forking": true,
                "is_template": false,
                "web_commit_signoff_required": false,
                "topics": [],
                "visibility": "public",
                "forks": 0,
                "open_issues": 4,
                "watchers": 0,
                "default_branch": "main",
                "allow_squash_merge": true,
                "allow_merge_commit": true,
                "allow_rebase_merge": true,
                "allow_auto_merge": false,
                "delete_branch_on_merge": false,
                "allow_update_branch": false,
                "use_squash_pr_title_as_default": false,
                "squash_merge_commit_message": "COMMIT_MESSAGES",
                "squash_merge_commit_title": "COMMIT_OR_PR_TITLE",
                "merge_commit_message": "PR_TITLE",
                "merge_commit_title": "MERGE_MESSAGE"
            }
        },
        "base": {
            "label": "lucasvanbriemen:main",
            "ref": "main",
            "sha": "ba9ecc26b0d567d57af1beb12254b80d415582a3",
            "user": {
                "login": "lucasvanbriemen",
                "id": 222973435,
                "node_id": "O_kgDODUpN-w",
                "avatar_url": "https://avatars.githubusercontent.com/u/222973435?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/lucasvanbriemen",
                "html_url": "https://github.com/lucasvanbriemen",
                "followers_url": "https://api.github.com/users/lucasvanbriemen/followers",
                "following_url": "https://api.github.com/users/lucasvanbriemen/following{/other_user}",
                "gists_url": "https://api.github.com/users/lucasvanbriemen/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/lucasvanbriemen/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/lucasvanbriemen/subscriptions",
                "organizations_url": "https://api.github.com/users/lucasvanbriemen/orgs",
                "repos_url": "https://api.github.com/users/lucasvanbriemen/repos",
                "events_url": "https://api.github.com/users/lucasvanbriemen/events{/privacy}",
                "received_events_url": "https://api.github.com/users/lucasvanbriemen/received_events",
                "type": "Organization",
                "user_view_type": "public",
                "site_admin": false
            },
            "repo": {
                "id": 1051816555,
                "node_id": "R_kgDOPrFyaw",
                "name": "github",
                "full_name": "lucasvanbriemen/github",
                "private": false,
                "owner": {
                    "login": "lucasvanbriemen",
                    "id": 222973435,
                    "node_id": "O_kgDODUpN-w",
                    "avatar_url": "https://avatars.githubusercontent.com/u/222973435?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/lucasvanbriemen",
                    "html_url": "https://github.com/lucasvanbriemen",
                    "followers_url": "https://api.github.com/users/lucasvanbriemen/followers",
                    "following_url": "https://api.github.com/users/lucasvanbriemen/following{/other_user}",
                    "gists_url": "https://api.github.com/users/lucasvanbriemen/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/lucasvanbriemen/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/lucasvanbriemen/subscriptions",
                    "organizations_url": "https://api.github.com/users/lucasvanbriemen/orgs",
                    "repos_url": "https://api.github.com/users/lucasvanbriemen/repos",
                    "events_url": "https://api.github.com/users/lucasvanbriemen/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/lucasvanbriemen/received_events",
                    "type": "Organization",
                    "user_view_type": "public",
                    "site_admin": false
                },
                "html_url": "https://github.com/lucasvanbriemen/github",
                "description": null,
                "fork": false,
                "url": "https://api.github.com/repos/lucasvanbriemen/github",
                "forks_url": "https://api.github.com/repos/lucasvanbriemen/github/forks",
                "keys_url": "https://api.github.com/repos/lucasvanbriemen/github/keys{/key_id}",
                "collaborators_url": "https://api.github.com/repos/lucasvanbriemen/github/collaborators{/collaborator}",
                "teams_url": "https://api.github.com/repos/lucasvanbriemen/github/teams",
                "hooks_url": "https://api.github.com/repos/lucasvanbriemen/github/hooks",
                "issue_events_url": "https://api.github.com/repos/lucasvanbriemen/github/issues/events{/number}",
                "events_url": "https://api.github.com/repos/lucasvanbriemen/github/events",
                "assignees_url": "https://api.github.com/repos/lucasvanbriemen/github/assignees{/user}",
                "branches_url": "https://api.github.com/repos/lucasvanbriemen/github/branches{/branch}",
                "tags_url": "https://api.github.com/repos/lucasvanbriemen/github/tags",
                "blobs_url": "https://api.github.com/repos/lucasvanbriemen/github/git/blobs{/sha}",
                "git_tags_url": "https://api.github.com/repos/lucasvanbriemen/github/git/tags{/sha}",
                "git_refs_url": "https://api.github.com/repos/lucasvanbriemen/github/git/refs{/sha}",
                "trees_url": "https://api.github.com/repos/lucasvanbriemen/github/git/trees{/sha}",
                "statuses_url": "https://api.github.com/repos/lucasvanbriemen/github/statuses/{sha}",
                "languages_url": "https://api.github.com/repos/lucasvanbriemen/github/languages",
                "stargazers_url": "https://api.github.com/repos/lucasvanbriemen/github/stargazers",
                "contributors_url": "https://api.github.com/repos/lucasvanbriemen/github/contributors",
                "subscribers_url": "https://api.github.com/repos/lucasvanbriemen/github/subscribers",
                "subscription_url": "https://api.github.com/repos/lucasvanbriemen/github/subscription",
                "commits_url": "https://api.github.com/repos/lucasvanbriemen/github/commits{/sha}",
                "git_commits_url": "https://api.github.com/repos/lucasvanbriemen/github/git/commits{/sha}",
                "comments_url": "https://api.github.com/repos/lucasvanbriemen/github/comments{/number}",
                "issue_comment_url": "https://api.github.com/repos/lucasvanbriemen/github/issues/comments{/number}",
                "contents_url": "https://api.github.com/repos/lucasvanbriemen/github/contents/{+path}",
                "compare_url": "https://api.github.com/repos/lucasvanbriemen/github/compare/{base}...{head}",
                "merges_url": "https://api.github.com/repos/lucasvanbriemen/github/merges",
                "archive_url": "https://api.github.com/repos/lucasvanbriemen/github/{archive_format}{/ref}",
                "downloads_url": "https://api.github.com/repos/lucasvanbriemen/github/downloads",
                "issues_url": "https://api.github.com/repos/lucasvanbriemen/github/issues{/number}",
                "pulls_url": "https://api.github.com/repos/lucasvanbriemen/github/pulls{/number}",
                "milestones_url": "https://api.github.com/repos/lucasvanbriemen/github/milestones{/number}",
                "notifications_url": "https://api.github.com/repos/lucasvanbriemen/github/notifications{?since,all,participating}",
                "labels_url": "https://api.github.com/repos/lucasvanbriemen/github/labels{/name}",
                "releases_url": "https://api.github.com/repos/lucasvanbriemen/github/releases{/id}",
                "deployments_url": "https://api.github.com/repos/lucasvanbriemen/github/deployments",
                "created_at": "2025-09-06T19:24:58Z",
                "updated_at": "2025-09-25T18:33:21Z",
                "pushed_at": "2025-09-25T18:33:18Z",
                "git_url": "git://github.com/lucasvanbriemen/github.git",
                "ssh_url": "git@github.com:lucasvanbriemen/github.git",
                "clone_url": "https://github.com/lucasvanbriemen/github.git",
                "svn_url": "https://github.com/lucasvanbriemen/github",
                "homepage": null,
                "size": 526,
                "stargazers_count": 0,
                "watchers_count": 0,
                "language": "PHP",
                "has_issues": true,
                "has_projects": true,
                "has_downloads": true,
                "has_wiki": false,
                "has_pages": false,
                "has_discussions": false,
                "forks_count": 0,
                "mirror_url": null,
                "archived": false,
                "disabled": false,
                "open_issues_count": 4,
                "license": null,
                "allow_forking": true,
                "is_template": false,
                "web_commit_signoff_required": false,
                "topics": [],
                "visibility": "public",
                "forks": 0,
                "open_issues": 4,
                "watchers": 0,
                "default_branch": "main",
                "allow_squash_merge": true,
                "allow_merge_commit": true,
                "allow_rebase_merge": true,
                "allow_auto_merge": false,
                "delete_branch_on_merge": false,
                "allow_update_branch": false,
                "use_squash_pr_title_as_default": false,
                "squash_merge_commit_message": "COMMIT_MESSAGES",
                "squash_merge_commit_title": "COMMIT_OR_PR_TITLE",
                "merge_commit_message": "PR_TITLE",
                "merge_commit_title": "MERGE_MESSAGE"
            }
        },
        "_links": {
            "self": {
                "href": "https://api.github.com/repos/lucasvanbriemen/github/pulls/6"
            },
            "html": {
                "href": "https://github.com/lucasvanbriemen/github/pull/6"
            },
            "issue": {
                "href": "https://api.github.com/repos/lucasvanbriemen/github/issues/6"
            },
            "comments": {
                "href": "https://api.github.com/repos/lucasvanbriemen/github/issues/6/comments"
            },
            "review_comments": {
                "href": "https://api.github.com/repos/lucasvanbriemen/github/pulls/6/comments"
            },
            "review_comment": {
                "href": "https://api.github.com/repos/lucasvanbriemen/github/pulls/comments{/number}"
            },
            "commits": {
                "href": "https://api.github.com/repos/lucasvanbriemen/github/pulls/6/commits"
            },
            "statuses": {
                "href": "https://api.github.com/repos/lucasvanbriemen/github/statuses/51fac72ac70bd2dd25e6ad1005c996598179ca05"
            }
        },
        "author_association": "CONTRIBUTOR",
        "auto_merge": null,
        "active_lock_reason": null
    },
    "repository": {
        "id": 1051816555,
        "node_id": "R_kgDOPrFyaw",
        "name": "github",
        "full_name": "lucasvanbriemen/github",
        "private": false,
        "owner": {
            "login": "lucasvanbriemen",
            "id": 222973435,
            "node_id": "O_kgDODUpN-w",
            "avatar_url": "https://avatars.githubusercontent.com/u/222973435?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/lucasvanbriemen",
            "html_url": "https://github.com/lucasvanbriemen",
            "followers_url": "https://api.github.com/users/lucasvanbriemen/followers",
            "following_url": "https://api.github.com/users/lucasvanbriemen/following{/other_user}",
            "gists_url": "https://api.github.com/users/lucasvanbriemen/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/lucasvanbriemen/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/lucasvanbriemen/subscriptions",
            "organizations_url": "https://api.github.com/users/lucasvanbriemen/orgs",
            "repos_url": "https://api.github.com/users/lucasvanbriemen/repos",
            "events_url": "https://api.github.com/users/lucasvanbriemen/events{/privacy}",
            "received_events_url": "https://api.github.com/users/lucasvanbriemen/received_events",
            "type": "Organization",
            "user_view_type": "public",
            "site_admin": false
        },
        "html_url": "https://github.com/lucasvanbriemen/github",
        "description": null,
        "fork": false,
        "url": "https://api.github.com/repos/lucasvanbriemen/github",
        "forks_url": "https://api.github.com/repos/lucasvanbriemen/github/forks",
        "keys_url": "https://api.github.com/repos/lucasvanbriemen/github/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/lucasvanbriemen/github/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/lucasvanbriemen/github/teams",
        "hooks_url": "https://api.github.com/repos/lucasvanbriemen/github/hooks",
        "issue_events_url": "https://api.github.com/repos/lucasvanbriemen/github/issues/events{/number}",
        "events_url": "https://api.github.com/repos/lucasvanbriemen/github/events",
        "assignees_url": "https://api.github.com/repos/lucasvanbriemen/github/assignees{/user}",
        "branches_url": "https://api.github.com/repos/lucasvanbriemen/github/branches{/branch}",
        "tags_url": "https://api.github.com/repos/lucasvanbriemen/github/tags",
        "blobs_url": "https://api.github.com/repos/lucasvanbriemen/github/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/lucasvanbriemen/github/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/lucasvanbriemen/github/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/lucasvanbriemen/github/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/lucasvanbriemen/github/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/lucasvanbriemen/github/languages",
        "stargazers_url": "https://api.github.com/repos/lucasvanbriemen/github/stargazers",
        "contributors_url": "https://api.github.com/repos/lucasvanbriemen/github/contributors",
        "subscribers_url": "https://api.github.com/repos/lucasvanbriemen/github/subscribers",
        "subscription_url": "https://api.github.com/repos/lucasvanbriemen/github/subscription",
        "commits_url": "https://api.github.com/repos/lucasvanbriemen/github/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/lucasvanbriemen/github/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/lucasvanbriemen/github/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/lucasvanbriemen/github/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/lucasvanbriemen/github/contents/{+path}",
        "compare_url": "https://api.github.com/repos/lucasvanbriemen/github/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/lucasvanbriemen/github/merges",
        "archive_url": "https://api.github.com/repos/lucasvanbriemen/github/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/lucasvanbriemen/github/downloads",
        "issues_url": "https://api.github.com/repos/lucasvanbriemen/github/issues{/number}",
        "pulls_url": "https://api.github.com/repos/lucasvanbriemen/github/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/lucasvanbriemen/github/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/lucasvanbriemen/github/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/lucasvanbriemen/github/labels{/name}",
        "releases_url": "https://api.github.com/repos/lucasvanbriemen/github/releases{/id}",
        "deployments_url": "https://api.github.com/repos/lucasvanbriemen/github/deployments",
        "created_at": "2025-09-06T19:24:58Z",
        "updated_at": "2025-09-25T18:33:21Z",
        "pushed_at": "2025-09-25T18:33:18Z",
        "git_url": "git://github.com/lucasvanbriemen/github.git",
        "ssh_url": "git@github.com:lucasvanbriemen/github.git",
        "clone_url": "https://github.com/lucasvanbriemen/github.git",
        "svn_url": "https://github.com/lucasvanbriemen/github",
        "homepage": null,
        "size": 526,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "PHP",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": false,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 4,
        "license": null,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [],
        "visibility": "public",
        "forks": 0,
        "open_issues": 4,
        "watchers": 0,
        "default_branch": "main",
        "custom_properties": {}
    },
    "organization": {
        "login": "lucasvanbriemen",
        "id": 222973435,
        "node_id": "O_kgDODUpN-w",
        "url": "https://api.github.com/orgs/lucasvanbriemen",
        "repos_url": "https://api.github.com/orgs/lucasvanbriemen/repos",
        "events_url": "https://api.github.com/orgs/lucasvanbriemen/events",
        "hooks_url": "https://api.github.com/orgs/lucasvanbriemen/hooks",
        "issues_url": "https://api.github.com/orgs/lucasvanbriemen/issues",
        "members_url": "https://api.github.com/orgs/lucasvanbriemen/members{/member}",
        "public_members_url": "https://api.github.com/orgs/lucasvanbriemen/public_members{/member}",
        "avatar_url": "https://avatars.githubusercontent.com/u/222973435?v=4",
        "description": ""
    },
    "sender": {
        "login": "lukaas-007",
        "id": 117530797,
        "node_id": "U_kgDOBwFgrQ",
        "avatar_url": "https://avatars.githubusercontent.com/u/117530797?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/lukaas-007",
        "html_url": "https://github.com/lukaas-007",
        "followers_url": "https://api.github.com/users/lukaas-007/followers",
        "following_url": "https://api.github.com/users/lukaas-007/following{/other_user}",
        "gists_url": "https://api.github.com/users/lukaas-007/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/lukaas-007/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/lukaas-007/subscriptions",
        "organizations_url": "https://api.github.com/users/lukaas-007/orgs",
        "repos_url": "https://api.github.com/users/lukaas-007/repos",
        "events_url": "https://api.github.com/users/lukaas-007/events{/privacy}",
        "received_events_url": "https://api.github.com/users/lukaas-007/received_events",
        "type": "User",
        "user_view_type": "public",
        "site_admin": false
    }
}


' />
    <button type="submit">Send</button>
  </form>

   <script>
    document.getElementById('myForm').addEventListener('submit', async function (e) {
      e.preventDefault();
      const payload = document.getElementById('payload').value;
      const event = document.getElementById('event').value;

      await fetch("{{ route('api.webhook') }}", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "X-github-event": event,
          "Accept": "application/json",
          "X-CSRF-TOKEN": document.querySelector('input[name="_token"]').value
        },
        body: payload
      });
    });
  </script>

</body>
</html>
